-- Orbit Chat initial schema.
-- IMPORTANT: Auth0 subject IDs are not Supabase Auth user UUIDs.
-- This migration enables RLS but intentionally creates no permissive policies.
-- Configure a verified Auth0 JWT bridge before granting database access.

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  auth0_sub text not null unique,
  display_name text not null default 'Usuario',
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.channels (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9-]{1,60}$'),
  name text not null,
  topic text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  channel_id bigint references public.channels(id) on delete cascade,
  channel_slug text not null,
  author_sub text not null,
  author_name text not null,
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists messages_channel_created_idx
  on public.messages (channel_slug, created_at desc);

alter table public.profiles enable row level security;
alter table public.channels enable row level security;
alter table public.messages enable row level security;

insert into public.channels (slug, name, topic)
values
  ('general', 'general', 'El punto de encuentro de la comunidad.'),
  ('presentaciones', 'presentaciones', 'Preséntate a la comunidad.'),
  ('memes', 'memes', 'Memes, clips y momentos épicos.'),
  ('ayuda', 'ayuda', 'Pide ayuda y ayuda a los demás.')
on conflict (slug) do nothing;

-- No RLS policies are granted until token verification is designed and tested.
-- Never put a Supabase service_role key in frontend code.